<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnqlKJi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnqlKJi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnqlKJi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnqlKJi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKnqlKJi\App_KernelDevDebugContainer([
    'container.build_hash' => 'KnqlKJi',
    'container.build_id' => 'bf513b61',
    'container.build_time' => 1687119194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnqlKJi');
